
server:
  port: 8082
  servlet:
    encoding:
      force-response: true

spring:
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/likelion-db2
    username: root
    password: 12345
  # swagger controll
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  # JPA controll
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update

jwt:
  secretKey: hello.world.ee.ff